export interface Project {
  src: string;
  caption?: string;
}

export const coursifyImages: Project[] = [
  { src: "/coursify/1.png" },
  { src: "/coursify/2.png" },
  { src: "/coursify/3.png" },
  { src: "/coursify/4.png" },
  { src: "/coursify/5.png" },
  { src: "/coursify/6.png" },
  { src: "/coursify/7.png" },
  { src: "/coursify/8.png" },
  { src: "/coursify/9.png" },
  { src: "/coursify/10.png" },
  { src: "/coursify/11.png" },
  { src: "/coursify/12.png" },
  { src: "/coursify/13.png" },
  { src: "/coursify/14.png" },
  { src: "/coursify/15.png" },
  { src: "/coursify/16.png" },
  { src: "/coursify/17.png" },
  { src: "/coursify/18.png" },
  { src: "/coursify/19.png" },
  { src: "/coursify/20.png" },
  { src: "/coursify/21.png" },
  { src: "/coursify/22.png" },
  { src: "/coursify/23.png" },
];

export const otasImages: Project[] = [
  { src: "/otas/1.png" },
  { src: "/otas/2.png" },
  { src: "/otas/3.png" },
  { src: "/otas/4.png" },
  { src: "/otas/5.png" },
  { src: "/otas/6.png" },
  { src: "/otas/7.png" },
  { src: "/otas/8.png" },
  { src: "/otas/9.png" },
  { src: "/otas/10.png" },
  { src: "/otas/11.png" },
  { src: "/otas/12.png" },
  { src: "/otas/13.png" },
  { src: "/otas/14.png" },
  { src: "/otas/15.png" },
  { src: "/otas/16.png" },
  { src: "/otas/17.png" },
  { src: "/otas/18.png" },
  { src: "/otas/19.png" },
  { src: "/otas/20.png" },
  { src: "/otas/21.png" },
  { src: "/otas/22.png" },
  { src: "/otas/23.png" },
  { src: "/otas/24.png" },
  { src: "/otas/25.png" },
  { src: "/otas/26.png" },
  { src: "/otas/27.png" },
  { src: "/otas/28.png" },
  { src: "/otas/29.png" },
  { src: "/otas/30.png" },
  { src: "/otas/31.png" },
  { src: "/otas/32.png" },
  { src: "/otas/33.png" },
  { src: "/otas/34.png" },
  { src: "/otas/35.png" },
  { src: "/otas/36.png" },
  { src: "/otas/37.png" },
  { src: "/otas/38.png" },
  { src: "/otas/39.png" },
  { src: "/otas/40.png" },
  { src: "/otas/41.png" },
  { src: "/otas/42.png" },
  { src: "/otas/43.png" },
  { src: "/otas/44.png" },
  { src: "/otas/45.png" },
  { src: "/otas/46.png" },
  { src: "/otas/47.png" },
  { src: "/otas/48.png" },
  { src: "/otas/49.png" },
  { src: "/otas/50.png" },
  { src: "/otas/51.png" },
  { src: "/otas/52.png" },
  { src: "/otas/53.png" },
  { src: "/otas/54.png" },
];

export const graduationProjectImages: Project[] = [
  { src: "/graduation-project/1.jpeg" },
  { src: "/graduation-project/2.jpeg" },
  { src: "/graduation-project/2.2.jpeg" },
  { src: "/graduation-project/3.jpeg" },
  { src: "/graduation-project/3.1.jpeg" },
  { src: "/graduation-project/4.jpeg" },
  { src: "/graduation-project/5.jpeg" },
  { src: "/graduation-project/6.jpeg" },
  { src: "/graduation-project/7.jpeg" },
  { src: "/graduation-project/8.jpeg" },
  { src: "/graduation-project/8.1.jpeg" },
  { src: "/graduation-project/9.jpeg" },
  { src: "/graduation-project/10.jpeg" },
  { src: "/graduation-project/10.1.jpeg" },
  { src: "/graduation-project/11.png" },
  { src: "/graduation-project/12.jpeg" },
  { src: "/graduation-project/12.1.jpeg" },
  { src: "/graduation-project/12.2.png" },
  { src: "/graduation-project/12.3.jpeg" },
  { src: "/graduation-project/13.jpeg" },
  { src: "/graduation-project/14.jpeg" },
  { src: "/graduation-project/15.jpeg" },
  { src: "/graduation-project/15.png" },
  { src: "/graduation-project/16.jpeg" },
  { src: "/graduation-project/16.png" },
];

export const courtProjectImages: Project[] = [
  { src: "/court-project/1.jpeg" },
  { src: "/court-project/2.jpeg" },
  { src: "/court-project/3.jpeg" },
  { src: "/court-project/4.jpeg" },
  { src: "/court-project/5.jpeg" },
  { src: "/court-project/6.jpeg" },
  { src: "/court-project/6.1.jpeg" },
  { src: "/court-project/7.jpeg" },
  { src: "/court-project/8.jpeg" },
  { src: "/court-project/9.jpeg" },
  { src: "/court-project/10.jpeg" },
  { src: "/court-project/11.jpeg" },
  { src: "/court-project/12.jpeg" },
  { src: "/court-project/13.jpeg" },
  { src: "/court-project/14.jpeg" },
  { src: "/court-project/15.jpeg" },
  { src: "/court-project/16.jpeg" },
  { src: "/court-project/17.jpeg" },
  { src: "/court-project/18.jpeg" },
  { src: "/court-project/19.jpeg" },
  { src: "/court-project/20.jpeg" },
  { src: "/court-project/22.jpeg" },
  { src: "/court-project/24.jpeg" },
  { src: "/court-project/26.jpeg" },
  { src: "/court-project/27.jpeg" },
  { src: "/court-project/28.jpeg" },
  { src: "/court-project/29.jpeg" },
];
